### ISSUE TITLE
Javascript debugging

### ISSUE THREAD

**Issue by Adidem-dev** [tumainimaganiko/Portfolio#15]
Weldone on your project. You've done great work. However, I discovered your form is accepting uppercase letters in the email box. 

The solution to this is to simply  use;

if (emailValue !== emailValue.toLowerCase()) {
    showError('Error: Email must be lowercase. Form is not sent.');
  } else {
    showError('');
    form.submit();
  }

**Comment by tumainimaganiko** [comment]
hey @Adidem-dev, I'm happy to get a suggestion on that and I assure you for now the form validation is fixed
