### ISSUE TITLE
Peer to peer code review

### ISSUE THREAD

**Issue by tumainimaganiko** [tumainimaganiko/Portfolio#5]
I'm happy to receive any suggestions

**Comment by Esmatullah12** [comment]
your website looks awesome and you did a great job 👏 However I noticed that you rewrite the code for each card again and again try to avoid re-writing the same code again and again. because, in coding, we have a principle DRY which basically means Don't Repeat Yourself.

**Comment by clin2on3mun** [comment]
Hi @tumainimaganiko 
Good job so far 👏 , there are a lot of things that can be done on this project in future just keep working on it.

**Comment by uno36** [comment]
Good job so far! 👍 @tumainimaganiko,
There are some changes that you still need to take into consideration before going to the next project, however, you are almost there! to improve semantics you can use a fieldset, to your form so that it is presented in a single box
